---
# Self-signed ClusterIssuer for bootstrapping
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Homelab CA Certificate (self-signed root)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Homelab CA
  subject:
    organizations:
      - Homelab
    organizationalUnits:
      - Infrastructure
  secretName: homelab-ca-secret
  duration: 87600h  # 10 years
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# ClusterIssuer using the Homelab CA
# Use this for all internal certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca-issuer
spec:
  ca:
    secretName: homelab-ca-secret
