---
# ExternalSecret for Git SSH credentials from Azure Key Vault
# Prerequisites:
#   az keyvault secret set --vault-name kv-dt-dev-pc-001 --name forgejo-ssh-private-key --file ~/.ssh/id_rsa_forgejo
#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-ssh-credentials
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: git-ssh-credentials
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        key: forgejo-ssh-private-key
---
# ExternalSecret for container registry credentials
# Prerequisites:
#   # Create dockerconfigjson for Forgejo registry
#   FORGEJO_USER="wostal"
#   FORGEJO_TOKEN="<token>"
#   kubectl create secret docker-registry registry-creds \
#     --docker-server=forgejo.tailc90e09.ts.net \
#     --docker-username=$FORGEJO_USER \
#     --docker-password=$FORGEJO_TOKEN \
#     --dry-run=client -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d > /tmp/dockerconfig.json
#   az keyvault secret set --vault-name kv-dt-dev-pc-001 --name forgejo-registry-dockerconfig --file /tmp/dockerconfig.json
#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: registry-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: forgejo-registry-dockerconfig
