---
# CI/CD WorkflowTemplate for building and pushing Docker images
# Uses a single pod with shared volume (no artifact storage required)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-cd-docker
  namespace: argo-workflows
spec:
  entrypoint: ci-cd-pipeline

  arguments:
    parameters:
      - name: repo-ssh-url
        default: ""
      - name: repo-http-url
        default: ""
      - name: branch
        default: "main"
      - name: commit-sha
        default: ""
      - name: image-name
        default: ""
      - name: platforms
        default: "linux/amd64"
      - name: event-type
        default: "push"
      - name: pr-number
        default: ""

  templates:
    - name: ci-cd-pipeline
      inputs:
        parameters:
          - name: repo-ssh-url
            default: "{{workflow.parameters.repo-ssh-url}}"
          - name: branch
            default: "{{workflow.parameters.branch}}"
          - name: commit-sha
            default: "{{workflow.parameters.commit-sha}}"
          - name: image-name
            default: "{{workflow.parameters.image-name}}"
      volumes:
        - name: ssh-key
          secret:
            secretName: git-ssh-credentials
            defaultMode: 0400
        - name: docker-config
          secret:
            secretName: registry-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: workspace
          emptyDir: {}
        - name: varlibcontainers
          emptyDir: {}
      securityContext:
        runAsUser: 0
      script:
        image: quay.io/buildah/stable:v1.35
        command: [/bin/sh]
        source: |
          set -e

          echo "============================================"
          echo "    CI/CD Pipeline for grafana-k6-custom"
          echo "============================================"
          echo ""
          echo "Repo: {{inputs.parameters.repo-ssh-url}}"
          echo "Branch: {{inputs.parameters.branch}}"
          echo "Image: {{inputs.parameters.image-name}}"
          echo ""

          # Install dependencies
          echo "=== Step 0: Install Dependencies ==="
          dnf install -y -q openssh-clients git

          # Configure SSH
          echo "=== Step 1: Configure SSH ==="
          mkdir -p ~/.ssh
          cp /ssh/id_rsa ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H forgejo.tailc90e09.ts.net >> ~/.ssh/known_hosts 2>/dev/null
          echo "SSH configured"

          # Clone repository
          echo ""
          echo "=== Step 2: Clone Repository ==="
          cd /workspace

          COMMIT_SHA="{{inputs.parameters.commit-sha}}"
          BRANCH="{{inputs.parameters.branch}}"

          if [ -n "$COMMIT_SHA" ] && [ "$COMMIT_SHA" != "" ]; then
            echo "Cloning at commit: $COMMIT_SHA"
            git clone {{inputs.parameters.repo-ssh-url}} repo
            cd repo
            git checkout $COMMIT_SHA
          else
            echo "Cloning branch: $BRANCH"
            git clone --depth 1 --branch $BRANCH {{inputs.parameters.repo-ssh-url}} repo
            cd repo
          fi

          COMMIT=$(git rev-parse HEAD)
          SHORT_SHA=$(echo $COMMIT | cut -c1-7)
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.1.0-$SHORT_SHA")

          echo "Commit: $COMMIT"
          echo "Version: $VERSION"
          echo "Files:"
          ls -la

          # Lint Dockerfile
          echo ""
          echo "=== Step 3: Lint Dockerfile ==="
          if [ -f Dockerfile ]; then
            echo "Dockerfile found, skipping hadolint (not installed in buildah image)"
          else
            echo "No Dockerfile found"
            exit 1
          fi

          # Build with Buildah
          echo ""
          echo "=== Step 4: Build Docker Image ==="
          IMAGE="{{inputs.parameters.image-name}}"

          # Configure registries and storage
          mkdir -p /etc/containers /var/lib/containers/storage /run/containers/storage
          cat > /etc/containers/registries.conf << 'EOF'
          unqualified-search-registries = ["docker.io"]
          EOF
          cat > /etc/containers/storage.conf << 'EOF'
          [storage]
          driver = "vfs"
          runroot = "/run/containers/storage"
          graphroot = "/var/lib/containers/storage"
          EOF

          buildah --storage-driver vfs build \
            --format docker \
            -t "$IMAGE:latest" \
            -t "$IMAGE:$VERSION" \
            -t "$IMAGE:sha-$SHORT_SHA" \
            .

          echo "Build complete"
          buildah --storage-driver vfs images

          # Push to registry
          echo ""
          echo "=== Step 5: Push to Registry ==="

          # Configure registry auth
          mkdir -p /run/containers/0
          cp /docker-config/config.json /run/containers/0/auth.json

          echo "Pushing $IMAGE:latest"
          buildah --storage-driver vfs push "$IMAGE:latest"

          echo "Pushing $IMAGE:$VERSION"
          buildah --storage-driver vfs push "$IMAGE:$VERSION"

          echo "Pushing $IMAGE:sha-$SHORT_SHA"
          buildah --storage-driver vfs push "$IMAGE:sha-$SHORT_SHA"

          echo ""
          echo "============================================"
          echo "    âœ… CI/CD Pipeline completed!"
          echo "============================================"
          echo ""
          echo "ðŸ³ Docker images pushed:"
          echo "   $IMAGE:latest"
          echo "   $IMAGE:$VERSION"
          echo "   $IMAGE:sha-$SHORT_SHA"
          echo ""
        volumeMounts:
          - name: ssh-key
            mountPath: /ssh
            readOnly: true
          - name: docker-config
            mountPath: /docker-config
            readOnly: true
          - name: workspace
            mountPath: /workspace
          - name: varlibcontainers
            mountPath: /var/lib/containers
