---
# CI/CD WorkflowTemplate for building and pushing Docker images
# Uses a single pod with shared volume (no artifact storage required)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-cd-docker
  namespace: argo-workflows
spec:
  entrypoint: ci-cd-pipeline

  arguments:
    parameters:
      - name: repo-ssh-url
        default: ""
      - name: repo-http-url
        default: ""
      - name: branch
        default: "main"
      - name: commit-sha
        default: ""
      - name: image-name
        default: ""
      - name: platforms
        default: "linux/amd64"
      - name: event-type
        default: "push"
      - name: pr-number
        default: ""

  templates:
    - name: ci-cd-pipeline
      inputs:
        parameters:
          - name: repo-ssh-url
            default: "{{workflow.parameters.repo-ssh-url}}"
          - name: branch
            default: "{{workflow.parameters.branch}}"
          - name: commit-sha
            default: "{{workflow.parameters.commit-sha}}"
          - name: image-name
            default: "{{workflow.parameters.image-name}}"
      volumes:
        - name: ssh-key
          secret:
            secretName: git-ssh-credentials
            defaultMode: 0400
        - name: docker-config
          secret:
            secretName: registry-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: workspace
          emptyDir: {}
      script:
        image: alpine:3.19
        command: [sh]
        source: |
          set -e

          echo "============================================"
          echo "    CI/CD Pipeline for grafana-k6-custom"
          echo "============================================"
          echo ""
          echo "Repo: {{inputs.parameters.repo-ssh-url}}"
          echo "Branch: {{inputs.parameters.branch}}"
          echo "Image: {{inputs.parameters.image-name}}"
          echo ""

          # Install dependencies
          apk add --no-cache git openssh-client curl

          # Configure SSH
          echo "=== Step 1: Configure SSH ==="
          mkdir -p ~/.ssh
          cp /ssh/id_rsa ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H forgejo.tailc90e09.ts.net >> ~/.ssh/known_hosts 2>/dev/null
          echo "SSH configured"

          # Clone repository
          echo ""
          echo "=== Step 2: Clone Repository ==="
          cd /workspace

          COMMIT_SHA="{{inputs.parameters.commit-sha}}"
          BRANCH="{{inputs.parameters.branch}}"

          if [ -n "$COMMIT_SHA" ] && [ "$COMMIT_SHA" != "" ]; then
            echo "Cloning at commit: $COMMIT_SHA"
            git clone {{inputs.parameters.repo-ssh-url}} repo
            cd repo
            git checkout $COMMIT_SHA
          else
            echo "Cloning branch: $BRANCH"
            git clone --depth 1 --branch $BRANCH {{inputs.parameters.repo-ssh-url}} repo
            cd repo
          fi

          COMMIT=$(git rev-parse HEAD)
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.1.0-$(git rev-parse --short HEAD)")

          echo "Commit: $COMMIT"
          echo "Version: $VERSION"
          echo "Files:"
          ls -la

          # Lint Dockerfile
          echo ""
          echo "=== Step 3: Lint Dockerfile ==="
          if [ -f Dockerfile ]; then
            # Download hadolint
            curl -sL https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
            chmod +x /usr/local/bin/hadolint
            hadolint --failure-threshold error Dockerfile
            echo "Dockerfile lint passed"
          else
            echo "No Dockerfile found, skipping lint"
          fi

          echo ""
          echo "=== Step 4: Build Info ==="
          echo "Image: {{inputs.parameters.image-name}}"
          echo "Tags:"
          echo "  - {{inputs.parameters.image-name}}:latest"
          echo "  - {{inputs.parameters.image-name}}:$VERSION"
          echo "  - {{inputs.parameters.image-name}}:sha-$(echo $COMMIT | cut -c1-7)"

          echo ""
          echo "============================================"
          echo "    Pipeline completed (build step skipped)"
          echo "============================================"
          echo ""
          echo "Note: Docker build requires Kaniko which needs"
          echo "to run in a separate container. For now, this"
          echo "pipeline validates clone and lint steps."
        volumeMounts:
          - name: ssh-key
            mountPath: /ssh
            readOnly: true
          - name: docker-config
            mountPath: /docker-config
            readOnly: true
          - name: workspace
            mountPath: /workspace
