---
# ExternalSecret for Kargo admin credentials
# Syncs Kargo admin password hash and token signing key from Azure Key Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-credentials
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: kargo-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Plain password for reference
        password: "{{ .password }}"
        # Kargo expects these exact keys (uppercase with underscores)
        ADMIN_ACCOUNT_PASSWORD_HASH: "{{ .passwordHash }}"
        ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: "{{ .tokenSigningKey }}"
  data:
    - secretKey: password
      remoteRef:
        key: kargo-admin-password
    - secretKey: passwordHash
      remoteRef:
        key: kargo-admin-password-hash
    - secretKey: tokenSigningKey
      remoteRef:
        key: kargo-token-signing-key
