---
# MetalLB IP Address Pool for k3d
# Uses IPs from k3d docker network (172.21.0.0/16)
# Range 172.21.255.1-172.21.255.254 to avoid conflicts with nodes
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 172.21.255.1-172.21.255.254
---
# L2 Advertisement - announce IPs via ARP
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
    - homelab-pool
