# Homelab InfluxDB config
adminUser:
  organization: "homelab"
  bucket: "mqtt"
  user: "admin"
  existingSecret: homelab-influxdb-credentials

# Enable persistence to prevent data loss on pod restarts
persistence:
  enabled: true
  storageClass: nfs-rwx
  accessMode: ReadWriteMany
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
