---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  gatewayClassName: istio
  listeners:
    - name: grafana-http
      hostname: grafana.devopslaboratory.org
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
