apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: cloudflared-tunnel-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials.json: |
          {"AccountTag":"588987ca16ff5dc7e60391ce0c9a9f38","TunnelSecret":"{{ .tunnelSecret }}","TunnelID":"9f0067e6-dfcb-4bc1-a12f-751763b7a14a"}
  data:
    - secretKey: tunnelSecret
      remoteRef:
        key: homelab-cloudflare-tunnel-secret
