---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: argocd
            helmRevision: "9.*"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: argocd-{{ .name }}
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/instance: argocd-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
    spec:
      project: platform-core
      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-cd
          targetRevision: "{{ .helmRevision }}"
          helm:
            releaseName: argocd
            valueFiles:
              - $values/values/argocd/common/values.yaml
              - $values/values/argocd/{{ .region }}/{{ .env }}/values.yaml
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          ref: values
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          path: extras/{{ .region }}/argocd
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      ignoreDifferences:
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[]?.remoteRef.conversionStrategy
            - .spec.data[]?.remoteRef.decodingStrategy
            - .spec.data[]?.remoteRef.metadataPolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
