---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: cert-manager
            helmRevision: "v1.17.*"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: cert-manager-{{ .name }}
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/instance: cert-manager-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
        argocd.argoproj.io/sync-wave: "-2"
    spec:
      project: platform-core
      sources:
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: "{{ .helmRevision }}"
          helm:
            releaseName: cert-manager
            parameters:
              - name: installCRDs
                value: "true"
            valueFiles:
              - $values/values/cert-manager/common/values.yaml
              - $values/values/cert-manager/{{ .region }}/{{ .env }}/values.yaml
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          path: extras/{{ .region }}/cert-manager
          directory:
            recurse: true
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          ref: values
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 10m
        managedNamespaceMetadata:
          labels:
            owner: argocd
            app.kubernetes.io/part-of: cert-manager
            region: "{{ .region }}"
            env: "{{ .env }}"
          annotations:
            argocd.argoproj.io/managed-by: "cert-manager-{{ .name }}"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
