---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cnpg
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: cnpg-system
            helmRevision: "0.26.*"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: cnpg-{{ .name }}
      labels:
        app.kubernetes.io/name: cnpg
        app.kubernetes.io/instance: cnpg-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: platform-storage
      sources:
        - repoURL: https://cloudnative-pg.github.io/charts
          chart: cloudnative-pg
          targetRevision: "{{ .helmRevision }}"
          helm:
            releaseName: cnpg
            valueFiles:
              - $values/values/cnpg/common/values.yaml
              - $values/values/cnpg/{{ .region }}/{{ .env }}/values.yaml
        - repoURL: git@github.com:tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          path: extras/{{ .region }}/cnpg
          directory:
            recurse: true
        - repoURL: git@github.com:tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          ref: values
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 10m
        managedNamespaceMetadata:
          labels:
            owner: argocd
            app.kubernetes.io/part-of: cnpg
            region: "{{ .region }}"
            env: "{{ .env }}"
          annotations:
            argocd.argoproj.io/managed-by: "cnpg-{{ .name }}"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
