---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: envoy-gateway-system
            helmRevision: "v1.4.6"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: envoy-gateway-{{ .name }}
      labels:
        app.kubernetes.io/name: envoy-gateway
        app.kubernetes.io/instance: envoy-gateway-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: platform-networking
      source:
        repoURL: docker.io/envoyproxy
        chart: gateway-helm
        targetRevision: "{{ .helmRevision }}"
        helm:
          releaseName: envoy-gateway
          valuesObject:
            config:
              envoyGateway:
                gateway:
                  controllerName: gateway.envoyproxy.io/gatewayclass-controller
                provider:
                  type: Kubernetes
            deployment:
              envoyGateway:
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 10m
        managedNamespaceMetadata:
          labels:
            owner: argocd
            app.kubernetes.io/part-of: envoy-gateway
            region: "{{ .region }}"
            env: "{{ .env }}"
          annotations:
            argocd.argoproj.io/managed-by: "envoy-gateway-{{ .name }}"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
