---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: homelab
            cluster: https://kubernetes.default.svc
            namespace: kargo
            helmRevision: "1.8.*"
            env: homelab
            region: local
            type: homelab
  template:
    metadata:
      name: kargo-{{ .name }}
      labels:
        app.kubernetes.io/name: kargo
        app.kubernetes.io/instance: kargo-{{ .name }}
        env: "{{ .env }}"
        cluster: "{{ .name }}"
        region: "{{ .region }}"
        type: "{{ .type }}"
      annotations:
        homelab.argocd.io/cluster-url: "{{ .cluster }}"
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: platform-delivery
      sources:
        - repoURL: ghcr.io/akuity/kargo-charts
          chart: kargo
          targetRevision: "{{ .helmRevision }}"
          helm:
            releaseName: kargo
            valueFiles:
              - $values/values/kargo/common/values.yaml
              - $values/values/kargo/{{ .region }}/{{ .env }}/values.yaml
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          path: extras/{{ .region }}/kargo
          directory:
            recurse: true
        - repoURL: ssh://git@forgejo.tailc90e09.ts.net/tomasz-wostal-eu/cd-homelab.git
          targetRevision: main
          ref: values
      destination:
        server: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      revisionHistoryLimit: 5
      info:
        - name: Region
          value: "{{ .region }}"
        - name: Environment
          value: "{{ .env }}"
        - name: Type
          value: "{{ .type }}"
        - name: Chart Version
          value: "{{ .helmRevision }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 10m
        managedNamespaceMetadata:
          labels:
            owner: argocd
            app.kubernetes.io/part-of: kargo
            region: "{{ .region }}"
            env: "{{ .env }}"
          annotations:
            argocd.argoproj.io/managed-by: "kargo-{{ .name }}"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true
