---
# EventSource for Forgejo (Gitea-compatible) webhooks
# Repository: https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom
#
# Webhook URL: https://argo-events-homelab.tailc90e09.ts.net/grafana-k6-custom
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: forgejo
  namespace: argo-events
spec:
  eventBusName: default
  webhook:
    grafana-k6-custom:
      # Webhook endpoint configuration
      port: "12000"
      endpoint: /grafana-k6-custom
      method: POST

      # Event filtering - accept only specific event types
      # Forgejo sends event type in X-Forgejo-Event header
      filter:
        expression: |
          (
            headers["X-Forgejo-Event"] == "push" ||
            headers["X-Forgejo-Event"] == "pull_request" ||
            headers["X-Forgejo-Event"] == "pull_request_sync"
          )
---
# Service for the EventSource webhook endpoint
# This is auto-created by Argo Events, but we define it explicitly
# for clarity and to ensure proper configuration
apiVersion: v1
kind: Service
metadata:
  name: forgejo-eventsource-svc
  namespace: argo-events
  labels:
    eventsource-name: forgejo
spec:
  type: ClusterIP
  ports:
    - port: 12000
      targetPort: 12000
      protocol: TCP
      name: webhook
  selector:
    eventsource-name: forgejo
    owner-name: forgejo