---
# ExternalSecret for Argo Events webhook secrets from Azure Key Vault
# Prerequisites:
#   az keyvault secret set --vault-name kv-dt-dev-pc-001 --name argo-events-webhook-secret --value "<random-secret>"
#   az keyvault secret set --vault-name kv-dt-dev-pc-001 --name forgejo-api-token --value "<forgejo-token>"
#
# Generate a secure webhook secret:
#   openssl rand -hex 32
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-events-webhook-credentials
  namespace: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: argo-events-webhook-credentials
    creationPolicy: Owner
  data:
    # Webhook secret for HMAC signature validation
    - secretKey: webhook-secret
      remoteRef:
        key: argo-events-webhook-secret
    # Forgejo API token (optional, for API calls in sensors)
    - secretKey: forgejo-token
      remoteRef:
        key: forgejo-api-token
