---
# Sensor for Forgejo webhook events
# Triggers CI/CD pipeline on push and pull_request events
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: forgejo-webhook
      eventSourceName: forgejo
      eventName: grafana-k6-custom
  triggers:
    - template:
        name: ci-cd-pipeline
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: grafana-k6-custom-
                namespace: argo-workflows
                labels:
                  workflows.argoproj.io/workflow-template: ci-cd-docker
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                    - name: commit-sha
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: event-type
                    - name: pr-number
          parameters:
            # Branch - from ref for push, from PR head for pull_request
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.ref
                value: "main"
              dest: spec.arguments.parameters.2.value
              operation: overwrite
            # Commit SHA
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.after
              dest: spec.arguments.parameters.3.value
              operation: overwrite
            # Fallback commit SHA for PR events
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.3.value
              operation: overwrite
            # Event type
            - src:
                dependencyName: forgejo-webhook
                dataKey: header.X-Forgejo-Event
              dest: spec.arguments.parameters.5.value
              operation: overwrite
            # PR number (if applicable)
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.pull_request.number
                value: ""
              dest: spec.arguments.parameters.6.value
              operation: overwrite
