---
# Sensor for Forgejo webhook events
# Parses webhook and triggers CI/CD pipeline
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: forgejo-webhook
      eventSourceName: forgejo
      eventName: grafana-k6-custom
  triggers:
    - template:
        name: ci-cd-pipeline
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: grafana-k6-custom-
                namespace: argo-workflows
                labels:
                  workflows.argoproj.io/workflow-template: ci-cd-docker
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    # Git parameters
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: ref
                      value: "refs/heads/main"
                    - name: commit-sha
                      value: ""
                    # Docker parameters
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: platforms
                      value: "linux/amd64"
                    # Event parameters
                    - name: event-type
                      value: "push"
                    - name: pr-number
                      value: ""
                    - name: pr-action
                      value: ""
                    # Sender info
                    - name: sender-login
                      value: ""
          parameters:
            # Event type from header
            - src:
                dependencyName: forgejo-webhook
                dataKey: header.X-Forgejo-Event.0
              dest: spec.arguments.parameters.8.value
            # Ref (for push events)
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.ref
              dest: spec.arguments.parameters.3.value
            # Commit SHA - from push (after) or PR (head.sha)
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.after
              dest: spec.arguments.parameters.4.value
            # Branch - extract from ref or PR head
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.ref
              dest: spec.arguments.parameters.2.value
            # PR number
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.9.value
            # PR action
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.action
              dest: spec.arguments.parameters.10.value
            # Sender login
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.sender.login
              dest: spec.arguments.parameters.11.value
            # For PR events - get commit from PR head
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.4.value
            # For PR events - get ref from PR head
            - src:
                dependencyName: forgejo-webhook
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.2.value
