---
# Sensor for Forgejo webhook events
# Triggers CI/CD pipeline on push and pull_request events
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: forgejo-webhook
      eventSourceName: forgejo
      eventName: grafana-k6-custom
  triggers:
    - template:
        name: ci-cd-pipeline
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: grafana-k6-custom-
                namespace: argo-workflows
                labels:
                  workflows.argoproj.io/workflow-template: ci-cd-docker
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: commit-sha
                      value: ""
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: event-type
                      value: "push"
                    - name: pr-number
                      value: ""
          # Parameters disabled for now - using defaults
          # TODO: re-enable when using real push/PR events
          parameters: []
