---
# Sensor for Forgejo webhook events
# Single dependency, trigger-level filtering for push vs pull_request
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: forgejo-event
      eventSourceName: forgejo
      eventName: grafana-k6-custom
  triggers:
    # ==================== PUSH TRIGGER ====================
    - template:
        name: push-pipeline
        conditions: "forgejo-event"
        conditionsReset:
          - byTime:
              cron: "* * * * *"
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: k6-push-
                namespace: argo-workflows
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: ref
                      value: "refs/heads/main"
                    - name: commit-sha
                      value: ""
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: platforms
                      value: "linux/amd64"
                    - name: event-type
                      value: "push"
                    - name: pr-number
                      value: ""
                    - name: pr-action
                      value: ""
                    - name: sender-login
                      value: ""
          parameters:
            - src:
                dependencyName: forgejo-event
                dataKey: body.ref
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.after
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.sender.login
              dest: spec.arguments.parameters.10.value
      retryStrategy:
        steps: 3
      # Only trigger for push events
      filtersLogicalOperator: "and"
      filters:
        data:
          - path: header.X-Forgejo-Event
            type: string
            value:
              - "push"

    # ==================== PR TRIGGER ====================
    - template:
        name: pr-pipeline
        conditions: "forgejo-event"
        conditionsReset:
          - byTime:
              cron: "* * * * *"
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: k6-pr-
                namespace: argo-workflows
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: ref
                      value: ""
                    - name: commit-sha
                      value: ""
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: platforms
                      value: "linux/amd64"
                    - name: event-type
                      value: "pull_request"
                    - name: pr-number
                      value: ""
                    - name: pr-action
                      value: ""
                    - name: sender-login
                      value: ""
          parameters:
            - src:
                dependencyName: forgejo-event
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.9.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.action
              dest: spec.arguments.parameters.10.value
            - src:
                dependencyName: forgejo-event
                dataKey: body.sender.login
              dest: spec.arguments.parameters.11.value
      retryStrategy:
        steps: 3
      # Only trigger for pull_request events
      filtersLogicalOperator: "and"
      filters:
        data:
          - path: header.X-Forgejo-Event
            type: string
            value:
              - "pull_request"
