---
# Sensor for Forgejo PUSH events
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo-push
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: push-event
      eventSourceName: forgejo
      eventName: grafana-k6-custom
      filters:
        data:
          - path: header.X-Forgejo-Event.0
            type: string
            value:
              - "push"
  triggers:
    - template:
        name: push-pipeline
        conditions: "push-event"
        conditionsReset:
          - byTime:
              cron: "* * * * *"
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: k6-push-
                namespace: argo-workflows
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: ref
                      value: "refs/heads/main"
                    - name: commit-sha
                      value: ""
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: platforms
                      value: "linux/amd64"
                    - name: event-type
                      value: "push"
                    - name: pr-number
                      value: ""
                    - name: pr-action
                      value: ""
                    - name: sender-login
                      value: ""
          parameters:
            - src:
                dependencyName: push-event
                dataKey: body.ref
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: push-event
                dataKey: body.after
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: push-event
                dataKey: body.sender.login
              dest: spec.arguments.parameters.10.value
      retryStrategy:
        steps: 3
---
# Sensor for Forgejo PULL REQUEST events
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: forgejo-pr
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: pr-event
      eventSourceName: forgejo
      eventName: grafana-k6-custom
      filters:
        data:
          - path: header.X-Forgejo-Event.0
            type: string
            value:
              - "pull_request"
  triggers:
    - template:
        name: pr-pipeline
        conditions: "pr-event"
        conditionsReset:
          - byTime:
              cron: "* * * * *"
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: k6-pr-
                namespace: argo-workflows
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: ci-cd-docker
                arguments:
                  parameters:
                    - name: repo-ssh-url
                      value: "git@forgejo.tailc90e09.ts.net:wostal/grafana-k6-custom.git"
                    - name: repo-http-url
                      value: "https://forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: branch
                      value: "main"
                    - name: ref
                      value: ""
                    - name: commit-sha
                      value: ""
                    - name: image-name
                      value: "forgejo.tailc90e09.ts.net/wostal/grafana-k6-custom"
                    - name: platforms
                      value: "linux/amd64"
                    - name: event-type
                      value: "pull_request"
                    - name: pr-number
                      value: ""
                    - name: pr-action
                      value: ""
                    - name: sender-login
                      value: ""
          parameters:
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.8.value
            - src:
                dependencyName: pr-event
                dataKey: body.action
              dest: spec.arguments.parameters.9.value
            - src:
                dependencyName: pr-event
                dataKey: body.sender.login
              dest: spec.arguments.parameters.10.value
      retryStrategy:
        steps: 3
