---
# CloudNative-PG Cluster for Authentik
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # Single instance for homelab
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "256MB"
      maintenance_work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "8MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2621kB"
      min_wal_size: "256MB"
      max_wal_size: "1GB"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik

  storage:
    size: 5Gi
    storageClass: nfs-rwx

  monitoring:
    enablePodMonitor: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
