---
# ConfigMap for Authentik domain configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config
  namespace: authentik
data:
  # Trust all proxies (Cloudflare, Istio Gateway)
  AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: "0.0.0.0/0,::/0"
  # Set the correct headers for proxy
  AUTHENTIK_WEB__HEADERS: "X-Forwarded-Proto"
