# ExternalSecret for cd-homelab repository
# Syncs SSH key from Azure Key Vault to ArgoCD repository secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-cd-homelab
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: argocd-repo-cd-homelab
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:tomasz-wostal-eu/cd-homelab.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-cd-homelab-ssh-key
