---
# ExternalSecret for Cloudflare API token
# Prerequisites:
#   az keyvault secret set --vault-name kv-dt-dev-pc-001 --name cloudflare-api-token --value "<your-api-token>"
#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: cloudflare-api-token
