---
# Central Gateway for homelab.local
# Listens on ports 80/443 (mapped by k3d)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  listeners:
    # HTTP (redirect to HTTPS)
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    # HTTPS with wildcard cert
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: homelab-wildcard-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
